
#ifndef NECTEREPARAMETERS_EXPORT_H
#define NECTEREPARAMETERS_EXPORT_H

#ifdef NECTEREPARAMETERS_STATIC_DEFINE
#  define NECTEREPARAMETERS_EXPORT
#  define NECTEREPARAMETERS_NO_EXPORT
#else
#  ifndef NECTEREPARAMETERS_EXPORT
#    ifdef NectereParameters_EXPORTS
        /* We are building this library */
#      define NECTEREPARAMETERS_EXPORT 
#    else
        /* We are using this library */
#      define NECTEREPARAMETERS_EXPORT 
#    endif
#  endif

#  ifndef NECTEREPARAMETERS_NO_EXPORT
#    define NECTEREPARAMETERS_NO_EXPORT 
#  endif
#endif

#ifndef NECTEREPARAMETERS_DEPRECATED
#  define NECTEREPARAMETERS_DEPRECATED __declspec(deprecated)
#endif

#ifndef NECTEREPARAMETERS_DEPRECATED_EXPORT
#  define NECTEREPARAMETERS_DEPRECATED_EXPORT NECTEREPARAMETERS_EXPORT NECTEREPARAMETERS_DEPRECATED
#endif

#ifndef NECTEREPARAMETERS_DEPRECATED_NO_EXPORT
#  define NECTEREPARAMETERS_DEPRECATED_NO_EXPORT NECTEREPARAMETERS_NO_EXPORT NECTEREPARAMETERS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef NECTEREPARAMETERS_NO_DEPRECATED
#    define NECTEREPARAMETERS_NO_DEPRECATED
#  endif
#endif

#endif /* NECTEREPARAMETERS_EXPORT_H */
