#pragma once

#define NECTERE_EVENT_TEMPLATE -1
//0 - 99
#define NECTERE_EVENT_UNKNOWN_ERROR 0
#define NECTERE_EVENT_MISFORMATTED 1
//600 - 699: Client instruction
#define NECTERE_EVENT_APP_LIST 600
#define NECTERE_EVENT_CMD_LIST 601
#define NECTERE_EVENT_STOP 666