#ifndef ARGUMENT_PARSER_DEFINITION_H_
#define ARGUMENT_PARSER_DEFINITION_H_

#include <limits.h>

#define PARG_NO_RESTRICTION 0
#define PARG_SIMPLE_DASH_RESTRICTION 1
#define PARG_DOUBLE_DASH_RESTRICTION 2

#define PARG_OPTIONNAL_VALUE 0
#define PARG_NEED_NO_VALUE 1
#define PARG_NEED_VALUE 2

#endif /* ARGUMENT_PARSER_DEFINITION_H_ */ 